version: '3'
services:
  flyway:
    image: flyway/flyway:6.3.1
    command: -url=jdbc:postgresql://postgres:5432/pancake  -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - ./flyway:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pancake